AWSTemplateFormatVersion: '2010-09-09'
Description: Create parameters and secrets for DB credentials.  Note: change subnets, SGs, and DB credentials for each environment.

Parameters:
  SecretName:
    Type: String
    Description: Name for the Secrets Manager secret
    Default: "database/custom-apps/costengine"
  DBUsername:
    Type: String
    Description: Database username
    Default: "ceuser"
  DBPassword:
    Type: String
    Description: Database password
    NoEcho: true
  DBHost:
    Type: String
    Description: Database host url
    Default: "or-rds-matma38-cost-engine-cluster.cluster-cn2wmyuvmuu5.us-west-2.rds.amazonaws.com"
  DBPort:
    Type: String
    Description: Database port
    Default: "3306"
  DBName:
    Type: String
    Description: Database Instance Name
    Default: "cemgr" 
 
# parameter store parameters.
  Subnetparameter:
    Type: String
    Description: "subnetIds for Lambda function deployments"
    Default: "subnet-649f1c13,subnet-1a0e637f"    
  Securitygroupparameter:
    Type: String
    Description: "SecurityGroups Ids for Lambda function deployments"
    Default: "sg-608a6404"  
    
Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: Secret for storing DB credentials
      SecretString:
        !Sub |
          {
            "engine": "mysql",
            "username": "${DBUsername}",
            "password": "${DBPassword}",
            "host": "${DBHost}",
            "dbname": "${DBName}",
            "port": "${DBPort}"
          }
      Tags:
        - Key: Environment
          Value: Prod
        - Key: Application
          Value: costengine

#################---parameter-store---#################
#######################################################

# stack name: costengine-services-parameters
###########--resources for parmater store---########### 
  Parameter1:
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: "StringList"
      Tier: Standard
      Name: "/costengine/lambda/subnetIds"
      Value: !Join
        - ","
        - - Ref: Subnetparameter

  Parameter2:
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: "StringList"
      Tier: Standard
      Name: "/costengine/lambda/securitygroupIds"
      Value: !Join
        - ","
        - - Ref: Securitygroupparameter
    
Outputs:
  SecretARN:
    Description: The ARN of the created Secrets Manager secret
    Value: !Ref DBSecret
